### PR TITLE
Editable task titles

### PR DESCRIPTION
**Pull request by mmstick**
This utilizes the new editable_input widget in libcosmic. Some further refinements will be necessary, but it's now possible to test the feature in practice here.

### CODE REVIEW

**Comment by edfloreshz** [comment]
Thanks Michael! 🎉

**Comment by mmstick** [comment]
Perhaps an editable input should not capture an event unless it is in write mode

**Comment by mmstick** [comment]
I will push a fix to libcosmic

**Comment by mmstick** [comment]
The fix is here: https://github.com/pop-os/libcosmic/pull/391

**Comment by edfloreshz** [comment]
How do you feel about a double click to edit the input?

**Comment by mmstick** [comment]
Looking at the keyboard shortcuts page, the spec says to make the text editable and focused on a single click, and select all text on a double click

**Comment by edfloreshz** [comment]
That sounds good as well.

**Pull request merged**
